### ISSUE TITLE
Exception in thread "Thread-18"

### ISSUE THREAD

**Issue by andrewkm** [SawFowl/CommandSync#17]
CommandSync 2.5.3
Paper 1.17.1 Build 409

On stop command:
```
[15:38:39] [Thread-18/WARN]: Exception in thread "Thread-18" java.lang.NullPointerException: Cannot invoke "Mr_Krab.CommandSyncClient.Bukkit.Locale.getString(String)" because the return value of "Mr_Krab.CommandSyncClient.Bukkit.CSC.getLocale()" is null
[15:38:39] [Thread-18/WARN]: 	at CommandSync-2.5.3-RELEASE-11.jar//Mr_Krab.CommandSyncClient.Bukkit.ClientThread.connect(ClientThread.java:121)
[15:38:39] [Thread-18/WARN]: 	at CommandSync-2.5.3-RELEASE-11.jar//Mr_Krab.CommandSyncClient.Bukkit.ClientThread.run(ClientThread.java:78)
```

**Comment by SawFowl** [comment]
I have not been able to catch this error. I will close the topic. If the problem occurs again, let me know.

**Comment by andrewkm** [comment]
It's happening continuously on the stop command, specifically when bungee is not running.

```
[19:33:43] [Thread-39/WARN]: Exception in thread "Thread-39" java.lang.NullPointerException: Cannot invoke "sawfowl.commandsyncclient.bukkit.Locale.getString(String)" because the return value of "sawfowl.commandsyncclient.bukkit.CSC.getLocale()" is null
[19:33:43] [Thread-39/WARN]: 	at CommandSync-2.8.4-RELEASE.jar//sawfowl.commandsyncclient.bukkit.ClientThread.run(ClientThread.java:42)
```

**Comment by andrewkm** [comment]
@SawFowl
