### ISSUE TITLE
Issues Connecting to Velocity Proxy Server

### ISSUE THREAD

**Issue by dparkinson101** [SawFowl/CommandSync#27]
Server Model:
I'm running Velocity 3.1.2-SNAPSHOT on the proxy and Paper 1.18.2 on my Survival Server.

Proxy: IP: localhost, Port 39999 Open, Pass: Pass123
Client Server: IP: 192.168.1.117(IP of Proxy Server On Network), No Ports Open, User: Survival, Pass: Pass123

After launching my survival server I get this warning in the console and it says "Cannot connect to server". 

```
[16:04:33 WARN]: Exception in thread "Thread-42" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.io.BufferedReader.readLine()" is null
[16:04:33 WARN]:        at CommandSync-2.8.2-RELEASE.jar//sawfowl.commandsyncclient.bukkit.ClientThread.connect(ClientThread.java:101)
[16:04:33 WARN]:        at CommandSync-2.8.2-RELEASE.jar//sawfowl.commandsyncclient.bukkit.ClientThread.run(ClientThread.java:78)
```

Any clue as to what is causing this?

**Comment by SawFowl** [comment]
A port must be available on the proxy server to connect. Otherwise, the plugin will not work.

**Comment by dparkinson101** [comment]
I have opened port 39999 on the proxy. See the following config files:
[config_proxy .txt](https://github.com/SawFowl/CommandSync/files/9066161/config_proxy.txt)
[config_client.txt](https://github.com/SawFowl/CommandSync/files/9066162/config_client.txt)
.

**Comment by SawFowl** [comment]
If the servers are located on different machines, then in the configuration on the proxy do not specify localhost, but the address of the proxy.

**Comment by dparkinson101** [comment]
they are in seperate docker containers on the same machine, I tried setting the proxy ip to be the local IP on the LAN but says it failed to bind. this IP has worked with other plugins that access the proxy such as Floodgate.

**Comment by dparkinson101** [comment]
I get this error when trying to assign that IP on the proxy server
```
[17:53:46 INFO] [CommandSync]: Configuration file loaded.
[17:53:46 ERROR]: java.net.BindException: Cannot assign requested address
[17:53:46 ERROR]:       at java.base/sun.nio.ch.Net.bind0(Native Method)
[17:53:46 ERROR]:       at java.base/sun.nio.ch.Net.bind(Net.java:555)
[17:53:46 ERROR]:       at java.base/sun.nio.ch.Net.bind(Net.java:544)
[17:53:46 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
[17:53:46 ERROR]:       at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
[17:53:46 ERROR]:       at java.base/java.net.ServerSocket.<init>(ServerSocket.java:274)
[17:53:46 ERROR]:       at sawfowl.commandsyncserver.velocity.CSS.onProxyInitialization(CSS.java:89)
[17:53:46 ERROR]:       at sawfowl.commandsyncserver.velocity.Lmbda$4.execute(Unknown Source)
[17:53:46 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[17:53:46 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[17:53:46 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[17:53:46 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:53:46 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:53:46 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by SawFowl** [comment]
I cannot guarantee the creation of a connection when working in a container.

**Comment by dparkinson101** [comment]
Figured it out, needed to use the docker bridge ip of 172.18.0.2 and it then managed to bind for some reason. Will close this ticket thanks for the help.
