### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Wgis** [SawFowl/CommandSync#29]
Gotta this error, but i see all work....
`[17:34:30 WARN]: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.io.BufferedReader.readLine()" is null
[17:34:30 WARN]: 	at CommandSync-2.8.2-RELEASE.jar//sawfowl.commandsyncclient.bukkit.ClientThread.connect(ClientThread.java:101)
[17:34:30 WARN]: 	at CommandSync-2.8.2-RELEASE.jar//sawfowl.commandsyncclient.bukkit.ClientThread.<init>(ClientThread.java:33)
[17:34:30 WARN]: 	at CommandSync-2.8.2-RELEASE.jar//sawfowl.commandsyncclient.bukkit.CSC.onEnable(CSC.java:35)
[17:34:30 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:34:30 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:34:30 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[17:34:30 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[17:34:30 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[17:34:30 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[17:34:30 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[17:34:30 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[17:34:30 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[17:34:30 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[17:34:30 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by SawFowl** [comment]
Most likely you have not configured the plugin correctly. Send me your configuration files on Discord - `SawFowl#2587`. 
Also specify which kernel you are using.

**Comment by Wgis** [comment]
Solved, use right port on clients
