### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by ColorsASD** [SawFowl/CommandSync#32]
I use Aegis Escanor 1.8.8

```
19:45:26 [WARNING] Exception encountered when loading plugin: CommandSync
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at sawfowl.commandsyncserver.bungee.CSS.onEnable(CSS.java:51)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:235)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:312)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:41)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:12)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:84)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:55)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 5 more
```

**Comment by SawFowl** [comment]
Have you read the documentation for the plugin?

Supported proxy:
- Velocity(plugin version 2.8+)
- BungeeCord(max plugin version 2.7 or use Velocity/WaterFall)
- WaterFall
- Other BungeeCord forks

**Comment by ColorsASD** [comment]
Read the error message and try to solve it. If you cannot, let me know whether you are unable or unwilling to solve it.
"Other BungeeCord forks." U are fuking joke. Useless support.
