### ISSUE TITLE
CommandSync freezes server on Pterodactyl Panel

### ISSUE THREAD

**Issue by Envqu** [SawFowl/CommandSync#33]
I using Pterodactyl Panel and I have a problem with CommandSync.
When I delete all CommandSync files and configure its working for some days.
But then after few weeks/month its just causing that server cant start until I delete CommandSync jar or CommandSync folder and configure like new one.

Thats the 2 last logs then server freezes:
```
[15:29:36 INFO]: [CommandSync] Enabling CommandSync v2.8.2*
[15:29:36 INFO]: Configuration file loaded.
```

**Comment by theDAVID543** [comment]
I have this issue too
and I found it appears 
```
[02:54:47 ERROR]: Exception in thread "Thread-2" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.io.BufferedReader.readLine()" is null
[02:54:47 ERROR]:       at sawfowl.commandsyncserver.velocity.ClientHandler.<init>(ClientHandler.java:42)
[02:54:47 ERROR]:       at sawfowl.commandsyncserver.velocity.ClientListener.run(ClientListener.java:20)
[04:14:59 ERROR]: [initial connection] /**.**.**.**:*****: read timed out
```
on the velocity console
and need to restart velocity to fix freezing

**Comment by SawFowl** [comment]
Uh, excuse me. I don't help with panel customization. I recommend using ssh only.

**Comment by ColorsASD** [comment]
The proxy server reserves the name for the backend server, so when you stop the backend server, the Proxy still sees that name as taken. Because of this, when the backend server starts up again, it cannot connect, which is why the Proxy has to be restarted. The developer could fix this, but if not, I can handle it myself as well. @SawFowl
