### ISSUE TITLE
Exception in thread "Thread-17" java.lang.NullPointerException: Cannot invoke 

### ISSUE THREAD

**Issue by hed516** [SawFowl/CommandSync#36]
[11:48:33 WARN]: Exception in thread "Thread-17" java.lang.NullPointerException: Cannot invoke "sawfowl.commandsyncclient.bukkit.Locale.getString(String, String[])" because the return value of "sawfowl.commandsyncclient.bukkit.CSC.getLocale()" is null
[11:48:33 WARN]:        at CommandSync-2.8.2-RELEASE.jar//sawfowl.commandsyncclient.bukkit.ClientThread.run(ClientThread.java:59)

**Comment by hed516** [comment]
Exception in thread "Thread-159" java.lang.NullPointerException: Cannot invoke "sawfowl.commandsyncclient.bukkit.Locale.getString(String, String[])" because the return value of "sawfowl.commandsyncclient.bukkit.CSC.getLocale()" is null
[11:48:34] [Thread-159/WARN]: 	at CommandSync-2.8.2-RELEASE.jar//sawfowl.commandsyncclient.bukkit.ClientThread.run(ClientThread.java:59)

**Comment by SawFowl** [comment]
What localization is specified in the plugin configuration?

**Comment by andrewkm** [comment]
@SawFowl we are getting the same thing on server shutdown.
Happens 1 in 10 times, but it does happen.
```
[16:44:11] [Thread-36/WARN]: Exception in thread "Thread-36" java.lang.NullPointerException: Cannot invoke "sawfowl.commandsyncclient.bukkit.Locale.getString(String)" because the return value of "sawfowl.commandsyncclient.bukkit.CSC.getLocale()" is null
[16:44:11] [Thread-36/WARN]: 	at CommandSync-2.8.4-RELEASE.jar//sawfowl.commandsyncclient.bukkit.ClientThread.connect(ClientThread.java:121)
[16:44:11] [Thread-36/WARN]: 	at CommandSync-2.8.4-RELEASE.jar//sawfowl.commandsyncclient.bukkit.ClientThread.run(ClientThread.java:78)
```

To answer your question to the original poster above, we use **lang=en_US**.
