### ISSUE TITLE
Can you support the new version of the original bungeecord!!!!!

### ISSUE THREAD

**Issue by hed516** [SawFowl/CommandSync#37]
Exception encountered when loading plugin: CommandSync
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
    at sawfowl.commandsyncserver.bungee.CSS.onEnable(CSS.java:51)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:266)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:298)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)

Can you support the new version of the original bungeecord!!!!!

**Comment by SawFowl** [comment]
Given the discontinuation of WaterFall development and the absolute unwillingness of md5 to use the same thing that developers of other server cores use, I'm going to have to reconsider working with loggers.
I think I'll have to split the logging work, though I don't want to do it for the sake of a single core proxy.

**Comment by SawFowl** [comment]
Fixed
